[build]
  base = "/"
  publish = "_site"
  command = "make build"


[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=60'''
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=3600'''
