[build]
  base = "/"
  publish = "_site"
  command = "make build"


[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=3600'''

[[redirects]]
  from = "https://www.kevinkuchta.com/*"
  to = "https://kevinhighwater.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kevinkuchta.com/*"
  to = "https://kevinhighwater.com/:splat"
  status = 301
  force = true